### ISSUE TITLE
travis > transfer.sh link expire after 15days. Could you manually launch one rebuilt please ? 

### ISSUE THREAD

**Issue by macfly1202** [thess/Prusa-Firmware#2]
After 15days, links from transfer.sh expire. So, could you click on 'Restart build' button on the right on the build history ? thanks. 

I suppose you could active the CRON job to run weekly in https://travis-ci.org/thess/Prusa-Firmware/settings? this will save the "issue" of expiration link (of transfer.sh) every 15 days if no commits in this branch of your repo

**Comment by thess** [comment]
Better yet - I've created tagged releases and will publish the ``.zip`` in the repo releases section. Only intermediate commits without a release tag will be in ``transfer.sh``.

New release here: https://github.com/thess/Prusa-Firmware/releases/download/v3.1.0r4/prusa3d_fw_v3.1.0r4.zip
