### ISSUE TITLE
Not an issue but question about first layer

### ISSUE THREAD

**Issue by macfly1202** [thess/Prusa-Firmware#4]
I see this in main repo about MK3 a new pull request about first layer issue. Is there any "chance" that this issue occurs with MK2 firmware too ? Because we all experience this after many print in comparison to cold start.
Sorry for the question :https://github.com/prusa3d/Prusa-Firmware/pull/514
thanks.

**Comment by stahlfabrik** [comment]
Hi! I am the author of this pull request!
I have not looked at the MK2 branch of the firmware.

The MK2 pinda does not have the thermistor inside so it does not know how warm it is. And temperature affects the height the PINDA triggers. 
So the exact mechanics are not in play there.

But I think the MK2 has a feature that one could enable where the PINDA gets preheated before a print and then quickly calibrated - is that true?

I mean, go for that code and have a thorough look at it! I REALLY DO NOT KNOW

**Comment by macfly1202** [comment]
@stahlfabrik : you true there is a preheat Pinda process that works very approximately I mean not consistant. Since the first day I own my mk2, I've no real issue with PLA but with ABS not same story and always dealing with Z live adjust between material is a bit painfull... Will take a closer look today if time. thanks

**Comment by macfly1202** [comment]
I close issue nothing to do here. By the way, firmware from Version 15-Mar-2018 (v3.1.0 r10) is amazing. My  MK2s MMU has never print so well (but must desactivate Temperature Calibration before print that create hole band). Strange to see Printer nearly stop at start and then accelerate. I put this in Slic3r custom code under filament settings : M900 K{if printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}0.47{else}0.08{endif}; Filament gcode. Don't know if it(s the right place but I really really happy with YOUR firmware...thanks
